"""Páginas por industria (src/pages/industria.html), en español e inglés.

Cada industria tiene su ruta en i18n.ROUTES ('ind-<id>') y estos textos:
desafíos, qué construimos (con enlaces a los tableros de ejemplo), los
indicadores que medimos, los casos y logos relacionados y preguntas
frecuentes. Los casos se toman de casos.py: solo se muestran los publicados.
No sumes resultados que no estén en un caso real.
"""

# Textos de la estructura de la página
LABELS = {
    'es': {
        'eyebrow': 'Industrias',
        'challenges': 'Los desafíos que vemos', 'challenges_title': 'Lo que frena a empresas como la tuya',
        'build': 'Qué construimos', 'build_title': 'Soluciones pensadas para tu negocio',
        'see_example': 'Ver el tablero de ejemplo', 'see_ai': 'Ver soluciones de IA',
        'kpis': 'Indicadores', 'kpis_title': 'Lo que medimos',
        'kpis_text': 'Definimos con tu equipo los indicadores clave y los calculamos todos los días con las mismas reglas.',
        'cases': 'Casos', 'cases_title': 'Resultados en el sector', 'see_case': 'Leer el caso',
        'cases_text': 'Proyectos reales, contados con los números que importan a cada cliente.',
        'example_caption': 'Tablero ilustrativo con datos ficticios.',
        'faq': 'Preguntas frecuentes', 'faq_title': 'Lo que nos suelen preguntar',
        'faq_more': '¿Tenés otra duda?', 'faq_write': 'Escribinos', 'faq_tail': 'y lo conversamos.',
        'whatsapp': 'o escribinos por WhatsApp',
        'cta_call': 'Coordinar una llamada',
        'trust': 'Trabajamos con',
        'other': 'Otras industrias',
        'posts': 'Blog', 'posts_title': 'Para seguir leyendo', 'minutes': 'min de lectura',
        'quiz': '¿Qué tan listos están tus datos? Hacé la autoevaluación de 2 minutos',
    },
    'en': {
        'eyebrow': 'Industries',
        'challenges': 'The challenges we see', 'challenges_title': 'What holds companies like yours back',
        'build': 'What we build', 'build_title': 'Solutions designed for your business',
        'see_example': 'See the sample dashboard', 'see_ai': 'See AI solutions',
        'kpis': 'KPIs', 'kpis_title': 'What we measure',
        'kpis_text': 'We define the key KPIs with your team and calculate them every day with the same rules.',
        'cases': 'Case studies', 'cases_title': 'Results in the sector', 'see_case': 'Read the case study',
        'cases_text': 'Real projects, told with the numbers that matter to each client.',
        'example_caption': 'Illustrative dashboard with sample data.',
        'faq': 'FAQ', 'faq_title': 'What we’re often asked',
        'faq_more': 'Have another question?', 'faq_write': 'Write to us', 'faq_tail': 'and let’s talk it through.',
        'whatsapp': 'or message us on WhatsApp',
        'cta_call': 'Book a call',
        'trust': 'We work with',
        'other': 'Other industries',
        'posts': 'Blog', 'posts_title': 'Further reading', 'minutes': 'min read',
        'quiz': 'How ready is your data? Take the 2-minute AI readiness check',
    },
}

# Datos comunes a los dos idiomas
# (casos de casos.py, tablero de ejemplo de dashboards.py, logos de src/logos.html y
# notas del blog, que se muestran solo en español)
COMMON = {
    'consumo': {'icon': 'cart3', 'cases': ['distribuidores', 'cobertura'], 'example': 'cobertura',
                'logos': ['kelloggs', 'mccain', 'cafe-m'],
                'posts': ['unificar-ventas-de-distribuidores', 'cobertura-y-venta-cruzada', 'kpis-comerciales']},
    'distribucion': {'icon': 'truck', 'cases': ['pronostico'], 'example': 'pronostico',
                     'logos': ['romemi'],
                     'posts': ['quiebre-de-stock-y-pronostico', 'pedidos-por-whatsapp', 'integrar-erp-con-agente-de-ia']},
    'pymes': {'icon': 'briefcase', 'cases': [], 'example': None,
              'logos': [],
              'posts': ['excel-o-power-bi', 'datos-antes-de-implementar-ia', 'donde-guardar-los-datos']},
    'retail': {'icon': 'shop', 'cases': [], 'example': 'pronostico',
               'logos': [],
               'posts': ['quiebre-de-stock-y-pronostico', 'kpis-comerciales', 'excel-o-power-bi']},
    'materiales': {'icon': 'lightning-charge', 'cases': [], 'example': 'cobertura',
                   'logos': ['romemi'],
                   'posts': ['pedidos-por-whatsapp', 'cobertura-y-venta-cruzada', 'calidad-de-datos']},
    'industria': {'icon': 'building-gear', 'cases': [], 'example': 'pronostico',
                  'logos': [],
                  'posts': ['quiebre-de-stock-y-pronostico', 'calidad-de-datos', 'integrar-erp-con-agente-de-ia']},
    'agro': {'icon': 'sprout', 'cases': [], 'example': None,
             'logos': [],
             'posts': ['excel-o-power-bi', 'pedidos-por-whatsapp', 'donde-guardar-los-datos']},
    'salud': {'icon': 'heart-pulse', 'cases': [], 'example': None,
              'logos': ['lilly'],
              'posts': ['kpis-comerciales', 'calidad-de-datos', 'donde-guardar-los-datos']},
}

TEXT = {
    'es': {
        'consumo': {
            'name': 'Consumo masivo',
            'title': 'Datos e IA para empresas de consumo masivo | DeepDatas',
            'description': 'Unificamos las ventas de tus distribuidores, medimos la cobertura de cada línea por punto de venta y anticipamos la demanda, con tableros y agentes de IA para el equipo comercial.',
            'h1': 'Datos e IA para consumo masivo: más ventas en cada', 'h1_em': 'punto de venta.',
            'lead': 'Unificamos las ventas de tus distribuidores, medimos la cobertura de cada línea y te mostramos dónde crecer, con tableros y agentes de IA que tu equipo comercial usa todos los días.',
            'card': 'Ventas de toda la red de distribuidores, cobertura por punto de venta y pronóstico de demanda.',
            'challenges': [
                ('Cada distribuidor informa a su manera', 'Las ventas llegan en planillas con formatos, códigos y criterios propios. Consolidarlas lleva días y el número final se discute.'),
                ('No sabés qué falta en cada punto de venta', 'Sabés cuánto vendés, pero no qué línea no compra cada cliente ni qué vendedor tiene más oportunidades de venta cruzada.'),
                ('Promociones difíciles de evaluar', 'Sin datos unificados es difícil saber qué promoción movió el volumen y cuánto margen costó.'),
                ('Quiebres en los picos y sobrestock después', 'La demanda estacional y las promociones complican la planificación de producción y reposición.'),
            ],
            'build': [
                ('bar-chart-line', 'Performance de la red de distribuidores', 'Ventas, volumen y cumplimiento del objetivo de cada distribuidor, con un tablero que se actualiza solo.', ('ejemplos', '#distribuidores')),
                ('people', 'Cobertura y venta cruzada por vendedor', 'Qué líneas compra cada punto de venta y listas de oportunidades para cada vendedor.', ('ejemplos', '#cobertura')),
                ('graph-up-arrow', 'Pronóstico de demanda', 'Modelos que anticipan la demanda por producto y zona para planificar producción y reposición.', ('ejemplos', '#pronostico')),
                ('robot', 'Agente de IA para el equipo comercial', 'Consultas en lenguaje natural sobre ventas, clientes y stock, desde el celular.', ('ia', '')),
            ],
            'kpis': ['Sell-in y sell-out por distribuidor', 'Cobertura numérica y ponderada', 'Venta cruzada por línea de producto',
                     'Cumplimiento de objetivos por zona y vendedor', 'Tamaño promedio de pedido', 'Frecuencia de compra y clientes perdidos',
                     'Quiebres de stock', 'Resultado de cada promoción', 'Margen por canal'],
            'faqs': [
                ('¿Los distribuidores tienen que cambiar cómo nos informan?', 'No. Automatizamos la recepción de los archivos tal como llegan hoy y unificamos formatos y códigos en el proceso.'),
                ('¿Podemos sumar datos de otras fuentes, como el CRM o las planillas de objetivos?', 'Sí. Integramos el ERP, el CRM, las planillas y los archivos de los distribuidores en un único modelo.'),
                ('¿Por dónde empezamos?', 'Por un diagnóstico de datos: en dos semanas sabés qué fuentes tenés y qué tablero o caso de IA conviene hacer primero.'),
            ],
            'cta_title': '¿Trabajás en consumo masivo? Empecemos por <em>tus datos.</em>',
        },
        'distribucion': {
            'name': 'Distribuidoras mayoristas',
            'title': 'Datos e IA para distribuidoras mayoristas | DeepDatas',
            'description': 'Pronóstico de demanda, reposición, rentabilidad por cliente y producto, y carga automática de pedidos con IA para distribuidoras mayoristas.',
            'h1': 'Datos e IA para distribuidoras: el stock justo,', 'h1_em': 'en el momento justo.',
            'lead': 'Integramos ventas, compras y stock en un solo modelo, anticipamos la demanda y automatizamos tareas como la carga de pedidos, para que compres mejor y no pierdas ventas.',
            'card': 'Pronóstico de demanda, reposición, rentabilidad por cliente y pedidos automáticos.',
            'challenges': [
                ('Quiebres y sobrestock al mismo tiempo', 'Las compras se planifican con promedios: algunos productos faltan en los picos y otros se acumulan en el depósito.'),
                ('Pedidos que se cargan a mano', 'Los pedidos llegan por WhatsApp y email en texto libre y alguien los copia al sistema, con demoras y errores.'),
                ('Miles de productos y clientes, poca visibilidad', 'Es difícil saber qué clientes, productos o canales dejan margen y cuáles no.'),
                ('Información repartida', 'Ventas en el ERP, e-commerce aparte y controles en planillas: cada área mira un número distinto.'),
            ],
            'build': [
                ('graph-up-arrow', 'Pronóstico y reposición', 'Un modelo que anticipa la demanda semanal y sugiere qué reponer antes de que falte.', ('ejemplos', '#pronostico')),
                ('inboxes', 'Carga automática de pedidos con IA', 'Un agente lee los pedidos de WhatsApp o email, los carga en tu sistema y avisa si falta algún dato.', ('ia', '')),
                ('bar-chart-line', 'Rentabilidad por cliente, producto y canal', 'Tableros de margen y mezcla de venta para decidir precios, descuentos y surtido.', None),
                ('bell', 'Alertas de clientes y stock', 'Avisos cuando un cliente deja de comprar o un producto está por quedarse sin stock.', ('ia', '')),
            ],
            'kpis': ['Nivel de servicio (fill rate)', 'Quiebres de stock', 'Días de inventario y rotación', 'Sobrestock y productos sin movimiento',
                     'Precisión del pronóstico', 'Margen por cliente, producto y canal', 'Ticket promedio y frecuencia de compra',
                     'Clientes inactivos', 'Tiempos de entrega'],
            'faqs': [
                ('¿Necesitamos mucho historial para el pronóstico?', 'Cuanto más historial, mejor, pero lo evaluamos en el diagnóstico: revisamos qué datos hay y qué precisión es razonable esperar antes de construir el modelo.'),
                ('¿El agente puede cargar pedidos en nuestro sistema?', 'Sí, si el sistema lo permite (por API o integración). Siempre empezamos con un piloto acotado y con controles para revisar lo que carga.'),
                ('¿Por dónde empezamos?', 'Por un diagnóstico de datos: en dos semanas sabés qué fuentes tenés y qué solución conviene hacer primero.'),
            ],
            'cta_title': '¿Tenés una distribuidora? Empecemos por <em>tus datos.</em>',
        },
        'pymes': {
            'name': 'Pymes',
            'title': 'Datos e IA para pymes: tu equipo de datos externo | DeepDatas',
            'description': 'Para pymes que gestionan con el ERP, Excel y WhatsApp: ordenamos tus datos, armamos tableros que se actualizan solos y sumamos IA donde ahorra tiempo, sin que tengas que formar un equipo de datos.',
            'h1': 'Datos e IA para pymes, sin tener que armar', 'h1_em': 'un equipo de datos.',
            'lead': 'Si hoy gestionás con el ERP, Excel y WhatsApp, empezamos por ahí: ordenamos tus datos, armamos los tableros que necesitás y te acompañamos mes a mes como tu equipo de datos externo.',
            'card': 'Sin equipo de datos propio: tu ERP, Excel y WhatsApp convertidos en tableros e IA.',
            'challenges': [
                ('Todo depende de Excel y de una persona', 'Los reportes los arma alguien a mano, lleva horas y, si esa persona no está, nadie sabe cómo se calculan.'),
                ('El sistema tiene los datos, pero no las respuestas', 'El ERP registra todo, pero sacar un análisis de ventas, márgenes o clientes implica exportar y cruzar planillas.'),
                ('No hay tiempo ni presupuesto para un área de datos', 'Contratar y retener especialistas en datos no tiene sentido para el tamaño de la empresa.'),
                ('La IA parece lejana', 'Se habla mucho de inteligencia artificial, pero no está claro por dónde empezar ni si tus datos están listos.'),
            ],
            'build': [
                ('bar-chart-line', 'Tableros que se actualizan solos', 'Ventas, márgenes, stock, cobranzas y clientes en un tablero de Power BI conectado a tu ERP y a tus planillas.', None),
                ('eraser', 'Datos ordenados', 'Unificamos clientes, productos y códigos para que los números cierren y todos miren lo mismo.', None),
                ('robot', 'Un primer caso de IA acotado', 'Por ejemplo, consultas por WhatsApp a tus indicadores o la carga automática de pedidos, con un piloto de alcance definido.', ('ia', '')),
                ('people', 'Tu equipo de datos externo', 'Mantenemos, mejoramos y ampliamos tus soluciones mes a mes, sin que tengas que contratar especialistas.', None),
            ],
            'kpis': ['Ventas y margen por cliente, producto y vendedor', 'Rentabilidad por línea de negocio', 'Stock, rotación y productos sin movimiento',
                     'Cuentas por cobrar y días de cobro', 'Clientes nuevos, activos e inactivos', 'Flujo de fondos proyectado',
                     'Gastos por rubro contra el presupuesto', 'Cumplimiento de objetivos'],
            'faqs': [
                ('¿Es para empresas de nuestro tamaño?', 'Sí. Trabajamos por etapas y con alcances acotados, para que cada paso tenga un resultado concreto.'),
                ('¿Tenemos que cambiar de sistema?', 'No. Trabajamos con el ERP que ya usás (Tango, Odoo, SAP u otro) y con tus planillas.'),
                ('¿Quién mantiene los tableros después?', 'Podemos dejarlos documentados para que tu equipo los use y los mantenga, o seguir acompañándote mes a mes como tu equipo de datos externo.'),
            ],
            'cta_title': '¿Tenés una pyme? Empecemos por <em>tus datos.</em>',
        },
        'retail': {
            'name': 'Retail y comercios',
            'title': 'Datos e IA para retail y cadenas de locales | DeepDatas',
            'description': 'Ventas, márgenes y stock por sucursal en un solo tablero, reposición sugerida y alertas, para cadenas de locales, franquicias y comercios con tienda online.',
            'h1': 'Datos e IA para retail: todas tus sucursales', 'h1_em': 'en un solo tablero.',
            'lead': 'Unificamos las ventas de tus locales y de tu tienda online, te mostramos qué sucursal, categoría o producto rinde y cuál no, y anticipamos qué reponer en cada local.',
            'card': 'Ventas, margen y stock por sucursal, reposición sugerida y tienda online integrada.',
            'challenges': [
                ('Cada local es una isla', 'Las ventas de cada sucursal, de la tienda online y de los marketplaces quedan en sistemas distintos, y compararlas exige armar planillas a mano.'),
                ('Stock que sobra en un local y falta en otro', 'Sin una vista del stock por sucursal es difícil decidir qué reponer, qué transferir y qué liquidar.'),
                ('Márgenes que se pierden sin que nadie lo note', 'Con precios y costos que cambian seguido, los descuentos y las promociones pueden comerse el margen de una categoría entera.'),
                ('Decisiones con datos del mes pasado', 'Los reportes llegan tarde y no muestran el ticket promedio ni el rendimiento de cada local o vendedor.'),
            ],
            'build': [
                ('bar-chart-line', 'Tablero de ventas por sucursal', 'Ventas, margen, ticket promedio y unidades por local, categoría y vendedor, comparados contra el año anterior y el objetivo.', None),
                ('graph-up-arrow', 'Reposición por sucursal', 'Un pronóstico de demanda que sugiere qué reponer en cada local y qué transferir entre sucursales.', ('ejemplos', '#pronostico')),
                ('cart3', 'Tienda online y locales integrados', 'Las ventas de la tienda online y de los marketplaces junto a las de los locales, con un solo stock y un solo número.', None),
                ('bell', 'Alertas de stock y margen', 'Avisos cuando un producto está por quedarse sin stock o cuando una categoría vende por debajo del margen esperado.', ('ia', '')),
            ],
            'kpis': ['Ventas por sucursal y por metro cuadrado', 'Ticket promedio y unidades por ticket', 'Margen por categoría y producto',
                     'Stock por sucursal y días de cobertura', 'Quiebres de stock', 'Rotación y productos sin movimiento',
                     'Ventas de la tienda online y de los marketplaces', 'Resultado de cada promoción', 'Ventas por vendedor'],
            'faqs': [
                ('¿Pueden integrar el sistema de los locales y la tienda online?', 'Sí. Integramos el sistema de los locales, la tienda online y los marketplaces (por ejemplo, Mercado Libre) en un único modelo, siempre que permitan exportar o consultar los datos.'),
                ('¿Sirve si tenemos pocas sucursales?', 'Sí. Con dos o tres locales ya conviene comparar ventas, márgenes y stock con las mismas reglas, y la solución crece a medida que sumás sucursales.'),
                ('¿Por dónde empezamos?', 'Por un diagnóstico de datos: en dos semanas sabés qué fuentes tenés y qué solución conviene hacer primero.'),
            ],
            'cta_title': '¿Tenés locales o una tienda online? Empecemos por <em>tus datos.</em>',
        },
        'materiales': {
            'name': 'Materiales eléctricos y construcción',
            'title': 'Datos e IA para distribuidoras de materiales eléctricos y de construcción | DeepDatas',
            'description': 'Catálogos de miles de artículos, listas de precios que cambian, pedidos por WhatsApp y cuentas corrientes: tableros, pronósticos y agentes de IA para distribuidoras de materiales eléctricos, corralones y ferreterías industriales.',
            'h1': 'Datos e IA para distribuidoras de materiales:', 'h1_em': 'miles de artículos, bajo control.',
            'lead': 'Ordenamos tu catálogo, tus listas de precios y tus ventas por cliente para que sepas qué reponer, a quién ofrecerle qué y dónde se te escapa el margen, y automatizamos la carga de pedidos.',
            'card': 'Catálogos grandes, listas de precios, pedidos por WhatsApp y venta cruzada a instaladores y obras.',
            'challenges': [
                ('Catálogos de miles de artículos', 'Códigos duplicados, descripciones distintas para el mismo producto y equivalencias entre marcas complican el stock y las compras.'),
                ('Listas de precios que cambian todo el tiempo', 'Cada actualización de los proveedores obliga a recalcular precios, y es fácil vender por debajo del costo de reposición sin darte cuenta.'),
                ('Pedidos por WhatsApp y por email', 'Instaladores y obras piden por mensaje, con fotos y descripciones informales, y alguien tiene que interpretarlos y cargarlos.'),
                ('Clientes que compran solo una parte', 'Un electricista o una constructora te compra cables pero no iluminación o protecciones, y nadie lo detecta a tiempo.'),
            ],
            'build': [
                ('eraser', 'Catálogo y maestro de artículos ordenados', 'Unificamos códigos, descripciones y equivalencias para que el stock, las compras y los reportes hablen de lo mismo.', None),
                ('bar-chart-line', 'Margen y precios bajo control', 'Tableros que comparan el precio de venta, el costo de reposición y los descuentos por cliente, marca y familia de productos.', None),
                ('inboxes', 'Carga automática de pedidos con IA', 'Un agente lee los pedidos de WhatsApp o email, identifica los artículos del catálogo y los carga en tu sistema para revisarlos.', ('ia', '')),
                ('people', 'Venta cruzada por cliente', 'Qué familias de productos compra cada cliente y listas de oportunidades para cada vendedor.', ('ejemplos', '#cobertura')),
            ],
            'kpis': ['Ventas y margen por familia, marca y cliente', 'Precio de venta contra costo de reposición', 'Descuentos por cliente y vendedor',
                     'Stock, rotación y artículos sin movimiento', 'Quiebres de stock', 'Venta cruzada por familia de productos',
                     'Clientes activos, nuevos e inactivos', 'Cuentas corrientes y días de cobro', 'Tiempos de preparación y entrega de pedidos'],
            'faqs': [
                ('Nuestro catálogo está desordenado, ¿podemos empezar igual?', 'Sí. Ordenar el maestro de artículos suele ser el primer paso, y lo hacemos con reglas que después se aplican solas a los artículos nuevos.'),
                ('¿El agente entiende pedidos escritos de manera informal?', 'Esa es la idea: interpreta descripciones como las que usan tus clientes y las relaciona con tu catálogo. Siempre empezamos con un piloto y con una revisión humana antes de confirmar cada pedido.'),
                ('¿Por dónde empezamos?', 'Por un diagnóstico de datos: en dos semanas sabés qué fuentes tenés y qué solución conviene hacer primero.'),
            ],
            'cta_title': '¿Tenés una distribuidora de materiales? Empecemos por <em>tus datos.</em>',
        },
        'industria': {
            'name': 'Industria y manufactura',
            'title': 'Datos e IA para la industria y pymes manufactureras | DeepDatas',
            'description': 'Costos por producto, planificación de la producción con pronósticos, stock de materias primas y tableros de planta para empresas industriales y pymes manufactureras.',
            'h1': 'Datos e IA para la industria: producción, costos y ventas', 'h1_em': 'en un solo lugar.',
            'lead': 'Integramos ventas, producción, compras y stock para que sepas cuánto te cuesta cada producto, qué producir y qué materias primas comprar antes de que falten.',
            'card': 'Costos por producto, planificación de la producción y stock de materias primas.',
            'challenges': [
                ('Costos que nadie termina de conocer', 'Con materias primas que cambian de precio seguido, es difícil saber el costo real y el margen de cada producto.'),
                ('Planificar la producción a ojo', 'Sin un pronóstico de ventas, se produce de más lo que no se vende y falta lo que sí.'),
                ('Materias primas que faltan o sobran', 'Las compras se deciden con poca anticipación y se mezclan urgencias, sobrestock y capital inmovilizado.'),
                ('La planta y la oficina, desconectadas', 'La producción, las mermas y las paradas se registran en planillas o en papel y no llegan a tiempo a quienes deciden.'),
            ],
            'build': [
                ('bar-chart-line', 'Costo y margen por producto', 'Un modelo que combina recetas, consumos y precios de compra para calcular el costo y el margen de cada producto y cliente.', None),
                ('graph-up-arrow', 'Pronóstico para planificar la producción', 'Anticipamos la demanda por producto para planificar qué producir y cuándo.', ('ejemplos', '#pronostico')),
                ('truck', 'Compras y stock de materias primas', 'Necesidades de compra según el plan de producción, el stock y los tiempos de entrega de cada proveedor.', None),
                ('gear', 'Tablero de planta', 'Producción, eficiencia, mermas y paradas por línea y por turno, cargadas de forma simple y actualizadas todos los días.', None),
            ],
            'kpis': ['Costo y margen por producto y cliente', 'Cumplimiento del plan de producción', 'Eficiencia por línea y turno',
                     'Mermas y desperdicios', 'Paradas y sus causas', 'Stock de materias primas y producto terminado',
                     'Precisión del pronóstico', 'Días de cobertura de insumos', 'Entregas a tiempo'],
            'faqs': [
                ('Gran parte de la planta registra en papel o en planillas, ¿sirve igual?', 'Sí. Empezamos con lo que hay y proponemos formas simples de cargar los datos (formularios o planillas con reglas), sin cambiar todo de golpe.'),
                ('¿Necesitamos sensores o un sistema de planta?', 'No para empezar. Muchos indicadores se calculan con los datos del ERP y los registros de producción. Si más adelante conviene sumar datos automáticos de las máquinas, lo evaluamos.'),
                ('¿Por dónde empezamos?', 'Por un diagnóstico de datos: en dos semanas sabés qué fuentes tenés y qué solución conviene hacer primero.'),
            ],
            'cta_title': '¿Tenés una empresa industrial? Empecemos por <em>tus datos.</em>',
        },
        'agro': {
            'name': 'Agro y agroindustria',
            'title': 'Datos e IA para el agro: acopios, insumos y agroindustria | DeepDatas',
            'description': 'Tableros de ventas por campaña, cuentas corrientes, stock de insumos y granos, y pronósticos para acopios, cooperativas, distribuidoras de insumos agropecuarios y agroindustrias.',
            'h1': 'Datos e IA para el agro: cada campaña,', 'h1_em': 'con números claros.',
            'lead': 'Unificamos ventas, stock, cuentas corrientes y datos de cada campaña en tableros simples, para que sepas qué productor compra qué, cuánto te deben y qué vas a necesitar en la próxima temporada.',
            'card': 'Ventas por campaña y productor, stock de insumos y granos, y cuentas corrientes.',
            'challenges': [
                ('Ventas muy estacionales', 'La demanda de insumos se concentra en pocas semanas por campaña, y un error de planificación se paga caro en stock o en ventas perdidas.'),
                ('Cuentas corrientes difíciles de seguir', 'Ventas a cosecha, canjes, monedas distintas y plazos largos hacen que saber cuánto te debe cada productor lleve tiempo.'),
                ('Información en planillas y en la cabeza de cada vendedor', 'Qué siembra cada cliente, cuántas hectáreas tiene y qué compró la campaña pasada no suele estar en ningún sistema.'),
                ('Stock repartido en plantas y depósitos', 'Insumos y granos en varios lugares, con movimientos que se registran tarde.'),
            ],
            'build': [
                ('bar-chart-line', 'Tablero comercial por campaña', 'Ventas, margen y participación por productor, zona, cultivo y vendedor, comparados con la campaña anterior.', None),
                ('graph-up-arrow', 'Planificación de la demanda de insumos', 'Estimamos qué va a necesitar cada zona en la próxima campaña a partir del historial de ventas y de lo que sabe tu equipo comercial.', None),
                ('clock-history', 'Cuentas corrientes y cobranzas', 'Saldos por productor, vencimientos y alertas de deuda, en pesos y en dólares.', None),
                ('robot', 'Agente de IA para los vendedores', 'Consultas desde el celular sobre las ventas, el saldo y el stock de cada cliente, también por WhatsApp.', ('ia', '')),
            ],
            'kpis': ['Ventas y margen por campaña, cultivo y zona', 'Participación en las compras de cada productor', 'Clientes nuevos, recurrentes y perdidos',
                     'Saldos y días de cobro por productor', 'Deuda vencida', 'Stock de insumos y granos por planta',
                     'Cumplimiento de objetivos por vendedor', 'Ventas a cosecha y canjes'],
            'faqs': [
                ('¿Pueden trabajar con ventas en pesos y en dólares?', 'Sí. Definimos con tu equipo cómo convertir y comparar los montos (por ejemplo, con el tipo de cambio de cada operación) y aplicamos siempre la misma regla.'),
                ('Mucha información está en planillas de cada vendedor, ¿la podemos usar?', 'Sí. Unificamos esas planillas con reglas claras y, si conviene, proponemos una forma simple de cargar los datos de cada productor para que no dependan de una persona.'),
                ('¿Por dónde empezamos?', 'Por un diagnóstico de datos: en dos semanas sabés qué fuentes tenés y qué solución conviene hacer primero.'),
            ],
            'cta_title': '¿Trabajás en el agro? Empecemos por <em>tus datos.</em>',
        },
        'salud': {
            'name': 'Laboratorios y salud',
            'title': 'Datos e IA para laboratorios y distribución farmacéutica | DeepDatas',
            'description': 'Tableros comerciales, priorización de la fuerza de ventas y seguimiento del stock en la cadena para laboratorios y distribución farmacéutica, con datos protegidos y permisos por rol.',
            'h1': 'Datos e IA para laboratorios: decisiones comerciales', 'h1_em': 'con datos confiables.',
            'lead': 'Integramos ventas, fuerza de ventas y stock en la cadena para que tu equipo comercial sepa dónde enfocar cada visita, con datos protegidos y permisos por rol.',
            'card': 'Tableros comerciales, foco para la fuerza de ventas y stock en la cadena, con datos protegidos.',
            'challenges': [
                ('Ventas que pasan por muchos intermediarios', 'Droguerías, distribuidoras y farmacias informan en formatos distintos y la visión de la demanda final llega tarde.'),
                ('Visitas sin una prioridad clara', 'Los representantes tienen agendas largas y pocos datos para decidir a quién visitar primero.'),
                ('Stock y vencimientos en la cadena', 'Sin seguimiento del stock en los canales, aparecen faltantes en un lugar y productos por vencer en otro.'),
                ('Datos que requieren cuidado', 'La información comercial y de clientes necesita permisos estrictos y trazabilidad de quién ve qué.'),
            ],
            'build': [
                ('bar-chart-line', 'Tablero comercial por zona, canal y producto', 'Ventas, objetivos y tendencias en un solo lugar, para la dirección y para cada gerente regional.', None),
                ('people', 'Foco para la fuerza de ventas', 'Listas priorizadas para cada representante, según potencial, frecuencia de visita y oportunidades.', None),
                ('truck', 'Stock y vencimientos en la cadena', 'Seguimiento del stock en distribuidores y alertas de faltantes y productos próximos a vencer.', None),
                ('robot', 'Agente de IA con permisos por rol', 'Consultas en lenguaje natural sobre los indicadores, donde cada persona ve solo lo que le corresponde.', ('ia', '')),
            ],
            'kpis': ['Ventas por canal, droguería y zona', 'Participación de mercado, cuando hay datos de auditoría', 'Cobertura de farmacias',
                     'Frecuencia y efectividad de las visitas', 'Cumplimiento de objetivos por representante', 'Stock en la cadena y días de cobertura',
                     'Productos próximos a vencer'],
            'faqs': [
                ('¿Cómo protegen información sensible?', 'Trabajamos con accesos de solo lectura y permisos por rol, firmamos acuerdos de confidencialidad y, siempre que es posible, implementamos la solución en la nube de tu empresa.'),
                ('¿Pueden integrar datos de auditoría de mercado?', 'Sí. Integramos los archivos de auditoría que recibe tu empresa con las ventas internas y los datos de la fuerza de ventas.'),
                ('¿Por dónde empezamos?', 'Por un diagnóstico de datos: en dos semanas sabés qué fuentes tenés y qué tablero o caso de IA conviene hacer primero.'),
            ],
            'cta_title': '¿Trabajás en un laboratorio? Empecemos por <em>tus datos.</em>',
        },
    },
    'en': {
        'consumo': {
            'name': 'Consumer goods',
            'title': 'Data and AI for consumer goods companies | DeepDatas',
            'description': 'We bring your distributors’ sales together, measure each product line’s coverage by point of sale and anticipate demand, with dashboards and AI agents for your sales team.',
            'h1': 'Data and AI for consumer goods: more sales at every', 'h1_em': 'point of sale.',
            'lead': 'We bring your distributors’ sales together, measure the coverage of each product line and show you where to grow, with dashboards and AI agents your sales team uses every day.',
            'card': 'Sales across your distributor network, point-of-sale coverage and demand forecasting.',
            'challenges': [
                ('Every distributor reports its own way', 'Sales arrive in spreadsheets with their own formats, codes and criteria. Consolidating them takes days and the final number is up for debate.'),
                ('You don’t know what each point of sale is missing', 'You know how much you sell, but not which line each customer doesn’t buy or which sales rep has the most cross-selling opportunities.'),
                ('Promotions that are hard to evaluate', 'Without unified data, it’s hard to tell which promotion moved volume and how much margin it cost.'),
                ('Stockouts at peak times, overstock afterwards', 'Seasonal demand and promotions make production and replenishment planning difficult.'),
            ],
            'build': [
                ('bar-chart-line', 'Distributor network performance', 'Sales, volume and target attainment for every distributor, in a dashboard that updates itself.', ('ejemplos', '#distribuidores')),
                ('people', 'Coverage and cross-selling by sales rep', 'Which lines each point of sale buys, and opportunity lists for every sales rep.', ('ejemplos', '#cobertura')),
                ('graph-up-arrow', 'Demand forecasting', 'Models that anticipate demand by product and region to plan production and replenishment.', ('ejemplos', '#pronostico')),
                ('robot', 'An AI agent for your sales team', 'Plain-language questions about sales, customers and inventory, right from their phone.', ('ia', '')),
            ],
            'kpis': ['Sell-in and sell-out by distributor', 'Numeric and weighted distribution', 'Cross-selling by product line',
                     'Target attainment by region and sales rep', 'Average order size', 'Purchase frequency and lost customers',
                     'Stockouts', 'Results of each promotion', 'Margin by channel'],
            'faqs': [
                ('Do our distributors have to change how they report?', 'No. We automate receiving their files exactly as they arrive today and unify formats and codes along the way.'),
                ('Can we add other sources, like the CRM or target spreadsheets?', 'Yes. We integrate the ERP, the CRM, spreadsheets and distributor files into a single model.'),
                ('Where do we start?', 'With a data assessment: in two weeks you’ll know which sources you have and which dashboard or AI use case to build first.'),
            ],
            'cta_title': 'In consumer goods? Let’s start with <em>your data.</em>',
        },
        'distribucion': {
            'name': 'Wholesale distribution',
            'title': 'Data and AI for wholesale distributors | DeepDatas',
            'description': 'Demand forecasting, replenishment, profitability by customer and product, and AI-powered order entry for wholesale distributors.',
            'h1': 'Data and AI for distributors: the right stock,', 'h1_em': 'at the right time.',
            'lead': 'We bring sales, purchasing and inventory into a single model, anticipate demand and automate tasks like order entry, so you buy smarter and stop losing sales.',
            'card': 'Demand forecasting, replenishment, customer profitability and automated order entry.',
            'challenges': [
                ('Stockouts and overstock at the same time', 'Purchasing is planned with averages: some products run out at peak times while others pile up in the warehouse.'),
                ('Orders entered by hand', 'Orders arrive by WhatsApp and email in free text and someone copies them into the system, with delays and errors.'),
                ('Thousands of products and customers, little visibility', 'It’s hard to know which customers, products or channels make money and which don’t.'),
                ('Scattered information', 'Sales in the ERP, e-commerce on its own and checks in spreadsheets: every department looks at a different number.'),
            ],
            'build': [
                ('graph-up-arrow', 'Forecasting and replenishment', 'A model that anticipates weekly demand and suggests what to restock before it runs out.', ('ejemplos', '#pronostico')),
                ('inboxes', 'AI-powered order entry', 'An agent reads WhatsApp or email orders, enters them into your system and flags anything that is missing.', ('ia', '')),
                ('bar-chart-line', 'Profitability by customer, product and channel', 'Margin and sales-mix dashboards to decide on prices, discounts and assortment.', None),
                ('bell', 'Customer and inventory alerts', 'Notifications when a customer stops buying or a product is about to run out of stock.', ('ia', '')),
            ],
            'kpis': ['Fill rate', 'Stockouts', 'Days of inventory and turnover', 'Overstock and slow-moving products',
                     'Forecast accuracy', 'Margin by customer, product and channel', 'Average ticket and purchase frequency',
                     'Inactive customers', 'Delivery times'],
            'faqs': [
                ('Do we need a lot of history for the forecast?', 'The more history, the better, but we evaluate it in the assessment: we review what data exists and what accuracy is reasonable to expect before building the model.'),
                ('Can the agent enter orders into our system?', 'Yes, if the system allows it (through an API or integration). We always start with a focused pilot and with checks to review what it enters.'),
                ('Where do we start?', 'With a data assessment: in two weeks you’ll know which sources you have and which solution to build first.'),
            ],
            'cta_title': 'Run a distribution business? Let’s start with <em>your data.</em>',
        },
        'pymes': {
            'name': 'Small and midsize businesses',
            'title': 'Data and AI for small and midsize businesses: your external data team | DeepDatas',
            'description': 'For businesses that run on their ERP, Excel and WhatsApp: we organize your data, build dashboards that update themselves and add AI where it saves time, without you having to build a data team.',
            'h1': 'Data and AI for small and midsize businesses, without building', 'h1_em': 'a data team.',
            'lead': 'If you run your business on your ERP, Excel and WhatsApp today, that’s where we start: we organize your data, build the dashboards you need and support you month after month as your external data team.',
            'card': 'No in-house data team: your ERP, Excel and WhatsApp turned into dashboards and AI.',
            'challenges': [
                ('Everything depends on Excel and one person', 'Someone builds the reports by hand, it takes hours and, if that person is away, nobody knows how they’re calculated.'),
                ('The system has the data, but not the answers', 'Your ERP records everything, but getting an analysis of sales, margins or customers means exporting and cross-referencing spreadsheets.'),
                ('No time or budget for a data department', 'Hiring and keeping data specialists doesn’t make sense for a company your size.'),
                ('AI feels out of reach', 'There’s a lot of talk about artificial intelligence, but it’s not clear where to start or whether your data is ready.'),
            ],
            'build': [
                ('bar-chart-line', 'Dashboards that update themselves', 'Sales, margins, inventory, collections and customers in a Power BI dashboard connected to your ERP and your spreadsheets.', None),
                ('eraser', 'Organized data', 'We unify customers, products and codes so the numbers add up and everyone looks at the same thing.', None),
                ('robot', 'A focused first AI use case', 'For example, asking about your KPIs on WhatsApp or automated order entry, with a clearly scoped pilot.', ('ia', '')),
                ('people', 'Your external data team', 'We maintain, improve and extend your solutions month after month, so you don’t have to hire specialists.', None),
            ],
            'kpis': ['Sales and margin by customer, product and sales rep', 'Profitability by business line', 'Inventory, turnover and slow-moving products',
                     'Accounts receivable and days to collect', 'New, active and inactive customers', 'Projected cash flow',
                     'Expenses by category vs. budget', 'Target attainment'],
            'faqs': [
                ('Is this for companies our size?', 'Yes. We work in stages with focused scopes, so every step delivers a concrete result.'),
                ('Do we have to change systems?', 'No. We work with the ERP you already use (Tango, Odoo, SAP or another) and with your spreadsheets.'),
                ('Who maintains the dashboards afterwards?', 'We can leave them documented so your team can use and maintain them, or keep supporting you month after month as your external data team.'),
            ],
            'cta_title': 'Run a small or midsize business? Let’s start with <em>your data.</em>',
        },
        'retail': {
            'name': 'Retail',
            'title': 'Data and AI for retail and store chains | DeepDatas',
            'description': 'Sales, margins and inventory by store in a single dashboard, suggested replenishment and alerts, for store chains, franchises and retailers with an online store.',
            'h1': 'Data and AI for retail: all your stores', 'h1_em': 'in a single dashboard.',
            'lead': 'We bring together sales from your stores and your online shop, show you which store, category or product performs and which doesn’t, and anticipate what to restock in each location.',
            'card': 'Sales, margin and inventory by store, suggested replenishment and an integrated online store.',
            'challenges': [
                ('Every store is an island', 'Sales from each store, the online shop and marketplaces live in different systems, and comparing them means building spreadsheets by hand.'),
                ('Too much stock in one store, too little in another', 'Without a view of inventory by store, it’s hard to decide what to restock, what to transfer and what to clear out.'),
                ('Margins that slip away unnoticed', 'With prices and costs changing often, discounts and promotions can eat up the margin of an entire category.'),
                ('Decisions based on last month’s data', 'Reports arrive late and don’t show the average ticket or how each store or salesperson is performing.'),
            ],
            'build': [
                ('bar-chart-line', 'Sales dashboard by store', 'Sales, margin, average ticket and units by store, category and salesperson, compared with last year and with target.', None),
                ('graph-up-arrow', 'Replenishment by store', 'A demand forecast that suggests what to restock in each store and what to transfer between locations.', ('ejemplos', '#pronostico')),
                ('cart3', 'Online and in-store sales together', 'Sales from your online store and marketplaces alongside your stores’ sales, with a single inventory and a single number.', None),
                ('bell', 'Inventory and margin alerts', 'Notifications when a product is about to run out or when a category sells below its expected margin.', ('ia', '')),
            ],
            'kpis': ['Sales by store and per square meter', 'Average ticket and units per ticket', 'Margin by category and product',
                     'Inventory by store and days of coverage', 'Stockouts', 'Turnover and slow-moving products',
                     'Online store and marketplace sales', 'Results of each promotion', 'Sales by salesperson'],
            'faqs': [
                ('Can you integrate our stores’ system and the online store?', 'Yes. We integrate your stores’ system, your online store and marketplaces (such as Mercado Libre) into a single model, as long as they let you export or query the data.'),
                ('Does it make sense if we only have a few stores?', 'Yes. With two or three stores it already pays to compare sales, margins and inventory with the same rules, and the solution grows as you add locations.'),
                ('Where do we start?', 'With a data assessment: in two weeks you’ll know which sources you have and which solution to build first.'),
            ],
            'cta_title': 'Have stores or an online shop? Let’s start with <em>your data.</em>',
        },
        'materiales': {
            'name': 'Electrical and building supplies',
            'title': 'Data and AI for electrical and building supply distributors | DeepDatas',
            'description': 'Catalogs with thousands of items, constantly changing price lists, WhatsApp orders and customer accounts: dashboards, forecasts and AI agents for electrical supply distributors, building supply yards and industrial hardware stores.',
            'h1': 'Data and AI for supply distributors:', 'h1_em': 'thousands of items, under control.',
            'lead': 'We clean up your catalog, your price lists and your sales by customer so you know what to restock, what to offer each customer and where you’re losing margin, and we automate order entry.',
            'card': 'Large catalogs, price lists, WhatsApp orders and cross-selling to contractors and job sites.',
            'challenges': [
                ('Catalogs with thousands of items', 'Duplicate codes, different descriptions for the same product and cross-brand equivalents make inventory and purchasing harder.'),
                ('Price lists that change all the time', 'Every supplier update means recalculating prices, and it’s easy to sell below replacement cost without noticing.'),
                ('Orders by WhatsApp and email', 'Contractors and job sites order by message, with photos and informal descriptions, and someone has to interpret them and enter them.'),
                ('Customers who buy only part of the range', 'An electrician or a construction company buys cable from you but not lighting or circuit protection, and nobody notices in time.'),
            ],
            'build': [
                ('eraser', 'A clean catalog and item master', 'We unify codes, descriptions and equivalents so inventory, purchasing and reports all speak the same language.', None),
                ('bar-chart-line', 'Margins and prices under control', 'Dashboards that compare selling price, replacement cost and discounts by customer, brand and product family.', None),
                ('inboxes', 'AI-powered order entry', 'An agent reads WhatsApp or email orders, matches the items to your catalog and enters them into your system for review.', ('ia', '')),
                ('people', 'Cross-selling by customer', 'Which product families each customer buys, and opportunity lists for every sales rep.', ('ejemplos', '#cobertura')),
            ],
            'kpis': ['Sales and margin by family, brand and customer', 'Selling price vs. replacement cost', 'Discounts by customer and sales rep',
                     'Inventory, turnover and slow-moving items', 'Stockouts', 'Cross-selling by product family',
                     'Active, new and inactive customers', 'Customer accounts and days to collect', 'Order picking and delivery times'],
            'faqs': [
                ('Our catalog is a mess. Can we still start?', 'Yes. Cleaning up the item master is usually the first step, and we do it with rules that then apply automatically to new items.'),
                ('Does the agent understand informally written orders?', 'That’s the idea: it interprets descriptions like the ones your customers use and matches them to your catalog. We always start with a pilot, and a person reviews each order before it’s confirmed.'),
                ('Where do we start?', 'With a data assessment: in two weeks you’ll know which sources you have and which solution to build first.'),
            ],
            'cta_title': 'Run a supply distribution business? Let’s start with <em>your data.</em>',
        },
        'industria': {
            'name': 'Manufacturing',
            'title': 'Data and AI for manufacturers and industrial SMEs | DeepDatas',
            'description': 'Cost by product, production planning with forecasts, raw material inventory and plant dashboards for manufacturers and industrial SMEs.',
            'h1': 'Data and AI for manufacturing: production, costs and sales', 'h1_em': 'in one place.',
            'lead': 'We integrate sales, production, purchasing and inventory so you know what each product really costs, what to produce and which raw materials to buy before they run out.',
            'card': 'Cost by product, production planning and raw material inventory.',
            'challenges': [
                ('Costs nobody fully knows', 'With raw material prices changing often, it’s hard to know the real cost and margin of each product.'),
                ('Planning production by gut feel', 'Without a sales forecast, you overproduce what doesn’t sell and run short of what does.'),
                ('Raw materials that run out or pile up', 'Purchasing decisions are made at short notice, mixing rush orders, overstock and tied-up capital.'),
                ('The plant and the office, disconnected', 'Output, waste and downtime are recorded on spreadsheets or paper and don’t reach decision-makers in time.'),
            ],
            'build': [
                ('bar-chart-line', 'Cost and margin by product', 'A model that combines bills of materials, consumption and purchase prices to calculate the cost and margin of each product and customer.', None),
                ('graph-up-arrow', 'Forecasting to plan production', 'We anticipate demand by product to plan what to produce and when.', ('ejemplos', '#pronostico')),
                ('truck', 'Raw material purchasing and inventory', 'Purchasing needs based on the production plan, inventory and each supplier’s lead times.', None),
                ('gear', 'Plant dashboard', 'Output, efficiency, waste and downtime by line and shift, recorded simply and updated every day.', None),
            ],
            'kpis': ['Cost and margin by product and customer', 'Production plan attainment', 'Efficiency by line and shift',
                     'Scrap and waste', 'Downtime and its causes', 'Raw material and finished goods inventory',
                     'Forecast accuracy', 'Days of supply coverage', 'On-time deliveries'],
            'faqs': [
                ('Much of our plant records data on paper or in spreadsheets. Does that work?', 'Yes. We start with what you have and propose simple ways to capture the data (forms or spreadsheets with rules), without changing everything at once.'),
                ('Do we need sensors or a plant system?', 'Not to get started. Many KPIs can be calculated from ERP data and production records. If adding automatic machine data makes sense later on, we’ll evaluate it.'),
                ('Where do we start?', 'With a data assessment: in two weeks you’ll know which sources you have and which solution to build first.'),
            ],
            'cta_title': 'Run a manufacturing company? Let’s start with <em>your data.</em>',
        },
        'agro': {
            'name': 'Agribusiness',
            'title': 'Data and AI for agribusiness: grain elevators, farm inputs and agro-industry | DeepDatas',
            'description': 'Sales dashboards by season, customer accounts, input and grain inventory, and forecasts for grain elevators, cooperatives, farm input distributors and agro-industrial companies.',
            'h1': 'Data and AI for agribusiness: every season,', 'h1_em': 'with clear numbers.',
            'lead': 'We bring sales, inventory, customer accounts and season data together in simple dashboards, so you know which grower buys what, how much they owe you and what you’ll need next season.',
            'card': 'Sales by season and grower, input and grain inventory, and customer accounts.',
            'challenges': [
                ('Highly seasonal sales', 'Demand for inputs is concentrated in a few weeks each season, and a planning mistake costs dearly in inventory or lost sales.'),
                ('Customer accounts that are hard to track', 'Sales paid at harvest, barter deals, different currencies and long terms make it time-consuming to know how much each grower owes you.'),
                ('Information in spreadsheets and in each rep’s head', 'What each customer plants, how many hectares they farm and what they bought last season is often not in any system.'),
                ('Inventory spread across plants and warehouses', 'Inputs and grain in several locations, with movements recorded late.'),
            ],
            'build': [
                ('bar-chart-line', 'Sales dashboard by season', 'Sales, margin and share by grower, region, crop and sales rep, compared with the previous season.', None),
                ('graph-up-arrow', 'Input demand planning', 'We estimate what each region will need next season based on sales history and what your sales team knows.', None),
                ('clock-history', 'Customer accounts and collections', 'Balances by grower, due dates and debt alerts, in pesos and in dollars.', None),
                ('robot', 'An AI agent for your sales reps', 'Questions from their phone about each customer’s sales, balance and inventory, including via WhatsApp.', ('ia', '')),
            ],
            'kpis': ['Sales and margin by season, crop and region', 'Share of each grower’s purchases', 'New, repeat and lost customers',
                     'Balances and days to collect by grower', 'Overdue debt', 'Input and grain inventory by plant',
                     'Target attainment by sales rep', 'Harvest-payment sales and barter deals'],
            'faqs': [
                ('Can you work with sales in pesos and in dollars?', 'Yes. We agree with your team on how to convert and compare amounts (for example, using each transaction’s exchange rate) and always apply the same rule.'),
                ('A lot of information is in each sales rep’s spreadsheets. Can we use it?', 'Yes. We unify those spreadsheets with clear rules and, if it helps, propose a simple way to record each grower’s data so it doesn’t depend on one person.'),
                ('Where do we start?', 'With a data assessment: in two weeks you’ll know which sources you have and which solution to build first.'),
            ],
            'cta_title': 'In agribusiness? Let’s start with <em>your data.</em>',
        },
        'salud': {
            'name': 'Pharma and healthcare',
            'title': 'Data and AI for pharmaceutical companies and distribution | DeepDatas',
            'description': 'Sales dashboards, sales force prioritization and supply chain inventory tracking for pharmaceutical companies and distributors, with protected data and role-based permissions.',
            'h1': 'Data and AI for pharma: commercial decisions', 'h1_em': 'backed by reliable data.',
            'lead': 'We integrate sales, sales force and supply chain inventory data so your commercial team knows where to focus every visit, with protected data and role-based permissions.',
            'card': 'Sales dashboards, sales force focus and supply chain inventory, with protected data.',
            'challenges': [
                ('Sales that go through many intermediaries', 'Wholesalers, distributors and pharmacies report in different formats, and visibility into end demand arrives late.'),
                ('Visits without clear priorities', 'Sales reps have long call lists and little data to decide whom to visit first.'),
                ('Inventory and expiry dates across the chain', 'Without tracking inventory in the channel, you get shortages in one place and products about to expire in another.'),
                ('Data that needs care', 'Commercial and customer information requires strict permissions and a clear record of who sees what.'),
            ],
            'build': [
                ('bar-chart-line', 'Sales dashboard by region, channel and product', 'Sales, targets and trends in one place, for leadership and for every regional manager.', None),
                ('people', 'Focus for your sales force', 'Prioritized lists for every sales rep, based on potential, visit frequency and opportunities.', None),
                ('truck', 'Inventory and expiry dates across the chain', 'Tracking of inventory at distributors and alerts for shortages and products nearing expiry.', None),
                ('robot', 'An AI agent with role-based permissions', 'Plain-language questions about your KPIs, where everyone sees only what they should.', ('ia', '')),
            ],
            'kpis': ['Sales by channel, wholesaler and region', 'Market share, when audit data is available', 'Pharmacy coverage',
                     'Visit frequency and effectiveness', 'Target attainment by sales rep', 'Channel inventory and days of coverage',
                     'Products nearing expiry'],
            'faqs': [
                ('How do you protect sensitive information?', 'We work with read-only access and role-based permissions, sign confidentiality agreements and, whenever possible, deploy the solution in your company’s cloud.'),
                ('Can you integrate market audit data?', 'Yes. We integrate the audit files your company receives with internal sales and sales force data.'),
                ('Where do we start?', 'With a data assessment: in two weeks you’ll know which sources you have and which dashboard or AI use case to build first.'),
            ],
            'cta_title': 'In pharma? Let’s start with <em>your data.</em>',
        },
    },
}

ORDER = ['consumo', 'distribucion', 'pymes', 'retail', 'materiales', 'industria', 'agro', 'salud']


def industries(lang):
    """Industrias en el orden del sitio, con los textos del idioma pedido."""
    return [{'id': key, **COMMON[key], **TEXT[lang][key]} for key in ORDER]
